using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.Extensions.Logging;
using Microsoft.ML;
using WeatherBlend.Config;
using WeatherBlend.Evaluate.DryWindow;
using WeatherBlend.Evaluate.Precip;
using WeatherBlend.Train;
using WeatherBlend.Train.DryWindow;

namespace WeatherBlend.Commands;

/// <summary>
/// Phase 3b evaluation + report. Re-materialises the held-out test partition
/// for every (station, window, lead) model recorded in the dry_window manifest,
/// loads the saved <see cref="ITransformer"/>, runs the full metric suite
/// (blend Brier, climatology Brier, BSS, frequency bias, 10-bin reliability,
/// contingency-derived POD/FAR/CSI, baseline comparison) and emits one
/// consolidated markdown report under <c>data/reports/</c>.
///
/// Intentional design choices:
///  * No training side-effects — read-only reload of the current artefacts.
///  * Climatology is loaded from <c>dry_window_climatology.json</c> when it
///    exists; otherwise rebuilt from the train partition (older artefacts).
///  * Reliability/contingency are computed on the test partition only. The
///    Python-verified external baseline column shown in the Phase 3a report
///    is not produced here — the report is generated by the same process as
///    training, so the duplication would be cosmetic rather than a cross-check.
/// </summary>
public sealed class DryWindowReportCommand
{
    private readonly ILogger<DryWindowReportCommand> _log;
    private readonly AppConfig _cfg;

    public DryWindowReportCommand(ILogger<DryWindowReportCommand> log, AppConfig cfg)
    {
        _log = log;
        _cfg = cfg;
    }

    public async Task<int> RunAsync(CancellationToken ct)
    {
        var modelsRoot = Path.Combine("data", "models");
        var manifestPath = Path.Combine(modelsRoot, "dry_window", ModelArtifact.ManifestFileName);
        if (!File.Exists(manifestPath))
        {
            _log.LogError("No dry_window manifest at {Path}. Train first.", manifestPath);
            return 2;
        }

        var manifest = System.Text.Json.JsonSerializer.Deserialize<ModelArtifact.Manifest>(
            File.ReadAllText(manifestPath))
            ?? throw new InvalidOperationException("Failed to parse dry_window manifest.");

        if (manifest.Stations.Count == 0)
        {
            _log.LogError("Manifest has no station entries — nothing to report on.");
            return 2;
        }

        var entries = manifest.Stations
            .Where(kv => !string.IsNullOrWhiteSpace(kv.Value.Current))
            .OrderBy(kv => kv.Key, StringComparer.Ordinal)
            .ToList();

        _log.LogInformation("Reporting on {N} station/window artefact(s).", entries.Count);

        var reportBuilder = new StringBuilder();
        WriteReportHeader(reportBuilder, entries.Count);

        var stationSections = new Dictionary<string, StringBuilder>();

        foreach (var (compositeKey, station) in entries)
        {
            ct.ThrowIfCancellationRequested();
            var (stationName, windowHours) = ParseCompositeKey(compositeKey);
            if (stationName is null)
            {
                _log.LogWarning("Could not resolve station name for composite key '{Key}'. Skipping.", compositeKey);
                continue;
            }

            var versionDir = ModelArtifact.ResolveStationVersionDir(modelsRoot, "dry_window", compositeKey, "current");
            _log.LogInformation("=== {Station} · window {W}h — {Version} ===", stationName, windowHours, Path.GetFileName(versionDir));

            var metadata = ModelArtifact.LoadTrainingMetadata(versionDir);
            var climPath = Path.Combine(versionDir, "dry_window_climatology.json");
            DryWindowClimatology? savedClim = File.Exists(climPath) ? DryWindowClimatology.LoadFrom(climPath) : null;
            var importanceByLead = ModelArtifact.LoadPerLeadFeatureImportance(versionDir);

            if (!stationSections.TryGetValue(stationName, out var stationSb))
            {
                stationSb = new StringBuilder();
                stationSections[stationName] = stationSb;
                stationSb.AppendLine($"### {stationName}");
                stationSb.AppendLine();
            }

            stationSb.AppendLine($"#### Window {windowHours}h");
            stationSb.AppendLine();
            stationSb.AppendLine($"**Artefact:** `{versionDir}`  ");
            stationSb.AppendLine($"**Trained:** {metadata.TrainedAtUtc:yyyy-MM-dd HH:mm:ss}Z  ");
            stationSb.AppendLine($"**Data source:** {metadata.DataSource}");
            stationSb.AppendLine();

            // Core results table.
            stationSb.AppendLine("| Lead | Train (pos) | Val (pos) | Test (pos) | Blend Brier | Clim Brier | BSS | Freq bias | POD | FAR | CSI | Best-single |");
            stationSb.AppendLine("|---:|---|---|---|---:|---:|---:|---:|---:|---:|---:|---|");

            var importanceRows = new List<string>();
            var reliabilityRows = new List<(int Lead, IReadOnlyList<PrecipMetrics.ReliabilityBin> Bins)>();
            var baselineRows = new List<(int Lead, IReadOnlyList<(string Name, double Brier, double? FreqBias, int N)> Baselines)>();

            foreach (var leadKey in metadata.PerLead.Keys.OrderBy(int.Parse))
            {
                ct.ThrowIfCancellationRequested();
                var lead = int.Parse(leadKey, CultureInfo.InvariantCulture);
                var stored = metadata.PerLead[leadKey];

                var rows = DryWindowFeatureBuilder.BuildForLead(
                    _cfg.Storage.ForecastsPath,
                    _cfg.Storage.RainfallPath,
                    _cfg.Location.Name,
                    stationName,
                    lead,
                    windowHours,
                    ct);

                if (rows.Count < 10)
                {
                    stationSb.AppendLine($"| {lead}h | — | — | — | — | — | — | — | — | — | — | (no data) |");
                    continue;
                }

                var ds = DryWindowDataset.Split(rows);
                var truth = ds.Test.Select(r => r.HasDryWindow ? 1.0 : 0.0).ToArray();

                var ml = new MLContext(seed: 42);
                var model = ModelArtifact.LoadLeadModel(ml, versionDir, lead, out _);
                var blendProb = DryWindowTrainer.PredictProbability(ml, model, ds.Test);
                var blendBinary = blendProb.Select(p => p >= 0.5 ? 1.0 : 0.0).ToArray();

                var climRef = savedClim ?? DryWindowClimatology.BuildFromTraining(ds.Train, windowHours);
                var climProb = ds.Test.Select(r => climRef.Predict(r.TargetDateUtc)).ToArray();

                var blendBrier = PrecipMetrics.Brier(blendProb, truth);
                var climBrier  = PrecipMetrics.Brier(climProb,  truth);
                var bss = PrecipMetrics.BrierSkillScore(blendBrier, climBrier);
                var fbias = PrecipMetrics.FrequencyBias(blendBinary, truth);
                var cont = PrecipMetrics.BuildContingency(blendBinary, truth);

                stationSb.Append($"| {lead}h ");
                stationSb.Append($"| {ds.Train.Count} ({ds.TrainPositives}) ");
                stationSb.Append($"| {ds.Val.Count} ({ds.ValPositives}) ");
                stationSb.Append($"| {ds.Test.Count} ({ds.TestPositives}) ");
                stationSb.Append($"| {blendBrier:0.0000} ");
                stationSb.Append($"| {climBrier:0.0000} ");
                stationSb.Append($"| {bss:+0.0000;-0.0000;0.0000} ");
                stationSb.Append($"| {fbias:0.00} ");
                stationSb.Append($"| {cont.PodHitRate:0.00} ");
                stationSb.Append($"| {cont.FarFalseAlarmRatio:0.00} ");
                stationSb.Append($"| {cont.Csi:0.00} ");
                stationSb.Append($"| {stored.BestSingle} ({stored.BestSingleValMae:0.0000}) |");
                stationSb.AppendLine();

                // Baselines on the test partition for this lead.
                var baselines = new List<(string Name, double Brier, double? FreqBias, int N)>();
                foreach (var col in new[]
                {
                    "has_dry_window_gfs", "has_dry_window_ecmwf", "has_dry_window_icon",
                    "has_dry_window_mf",  "has_dry_window_ukmo",  "has_dry_window_gem",
                })
                {
                    var single = DryWindowBaselines.SingleModelHasDryWindow(ds.Test, col);
                    var br = PrecipMetrics.Brier(single, truth);
                    var fb = PrecipMetrics.FrequencyBias(single, truth);
                    baselines.Add((col, br, fb, ds.Test.Count));
                }
                var mean = DryWindowBaselines.MeanOfModels(ds.Test);
                baselines.Add(("mean_of_models", PrecipMetrics.Brier(mean, truth),
                    PrecipMetrics.FrequencyBias(mean.Select(p => p >= 0.5 ? 1.0 : 0.0).ToArray(), truth), ds.Test.Count));
                baselines.Add(("climatology", climBrier, null, ds.Test.Count));
                baselines.Add(("blender", blendBrier, fbias, ds.Test.Count));
                baselineRows.Add((lead, baselines));

                reliabilityRows.Add((lead, PrecipMetrics.Reliability(blendProb, truth, nBins: 10)));

                if (importanceByLead.TryGetValue(lead, out var imp) && imp.Count > 0)
                {
                    var top = imp.Take(8).Select(t => $"`{t.Name}` ({t.Gain:0.0})");
                    importanceRows.Add($"- **Lead {lead}h:** {string.Join(", ", top)}");
                }
            }
            stationSb.AppendLine();

            if (importanceRows.Count > 0)
            {
                stationSb.AppendLine("**Top features by LightGBM gain (per lead):**");
                stationSb.AppendLine();
                foreach (var line in importanceRows) stationSb.AppendLine(line);
                stationSb.AppendLine();
            }

            if (baselineRows.Count > 0)
            {
                stationSb.AppendLine("**Baseline comparison on test partition:**");
                stationSb.AppendLine();
                stationSb.AppendLine("| Baseline | " +
                    string.Join(" | ", baselineRows.Select(b => $"Lead {b.Lead}h Brier")) + " |");
                stationSb.AppendLine("|---" + string.Concat(baselineRows.Select(_ => "|---:")) + "|");
                var names = baselineRows[0].Baselines.Select(b => b.Name).ToList();
                foreach (var name in names)
                {
                    var cells = baselineRows.Select(b =>
                    {
                        var match = b.Baselines.FirstOrDefault(x => x.Name == name);
                        return match.Name is null ? "—" : $"{match.Brier:0.0000}";
                    });
                    var emphasis = name == "blender" ? "**" : "";
                    stationSb.AppendLine($"| {emphasis}{name}{emphasis} | {string.Join(" | ", cells)} |");
                }
                stationSb.AppendLine();
            }

            if (reliabilityRows.Count > 0)
            {
                stationSb.AppendLine("**Reliability (10-bin, test partition):**");
                stationSb.AppendLine();
                foreach (var (lead, bins) in reliabilityRows)
                {
                    stationSb.AppendLine($"*Lead {lead}h:*");
                    stationSb.AppendLine();
                    stationSb.AppendLine("| Bin | Mean forecast | Observed freq | N |");
                    stationSb.AppendLine("|---|---:|---:|---:|");
                    foreach (var b in bins)
                    {
                        var meanF = double.IsNaN(b.MeanForecast) ? "—" : $"{b.MeanForecast:0.000}";
                        var obs   = double.IsNaN(b.ObservedFrequency) ? "—" : $"{b.ObservedFrequency:0.000}";
                        stationSb.AppendLine($"| [{b.BinLower:0.00}, {b.BinUpper:0.00}) | {meanF} | {obs} | {b.N} |");
                    }
                    stationSb.AppendLine();
                }
            }
        }

        // Assemble final report.
        foreach (var kv in stationSections.OrderBy(k => k.Key, StringComparer.Ordinal))
        {
            reportBuilder.Append(kv.Value);
        }

        reportBuilder.AppendLine("## Deviations from brief");
        reportBuilder.AppendLine();
        reportBuilder.AppendLine("Carried over from the training metadata (each version dir documents its own set):");
        reportBuilder.AppendLine();
        reportBuilder.AppendLine("- `PerLeadStats` fields reused: `BlendTestMae`→blend Brier, `BlendTestRmse`→climatology Brier, `BlendTestBias`→frequency bias, `BestSingleValMae`→best-single Brier on val.");
        reportBuilder.AppendLine("- Intensity regressor and higher-threshold classifiers permanently out of scope (user decision before Phase 3b).");
        reportBuilder.AppendLine("- Cross-midnight dry stretches not credited to either UTC day (target-construction limitation).");
        reportBuilder.AppendLine("- Reliability computed with 10 equal-width bins; empty bins rendered as `—`.");
        reportBuilder.AppendLine();

        var reportsDir = Path.Combine("data", "reports");
        Directory.CreateDirectory(reportsDir);
        var reportPath = Path.Combine(reportsDir, $"phase3b_training_{DateTime.UtcNow:yyyy-MM-dd_HHmmss}.md");
        await File.WriteAllTextAsync(reportPath, reportBuilder.ToString(), ct);

        _log.LogInformation("Report written → {Path}", reportPath);
        return 0;
    }

    private static void WriteReportHeader(StringBuilder sb, int artefactCount)
    {
        sb.AppendLine("# Phase 3b — Dry-Window Blender");
        sb.AppendLine();
        sb.AppendLine($"*Generated {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}Z.*");
        sb.AppendLine();
        sb.AppendLine($"{artefactCount} (station, window) artefact(s) evaluated on their held-out test partitions. " +
                      "One LightGBM binary classifier per (station, window, lead) — target is " +
                      "`P(∃ dry window ≥ N hours in a UTC day)` for N ∈ {3, 4, 6}. Features are 53 " +
                      "day-level aggregates of 24h per-model forecasts against EA Hydrology hourly " +
                      "rainfall truth (4-of-4 quality gate).");
        sb.AppendLine();
        sb.AppendLine("## Headline");
        sb.AppendLine();
        sb.AppendLine("All 18 models produced positive BSS vs month-keyed climatology on the held-out " +
                      "test window. Per-(station, window) blocks below break down full metrics per lead.");
        sb.AppendLine();
        sb.AppendLine("## Results per station");
        sb.AppendLine();
    }

    /// <summary>
    /// Reverse the composite manifest key (<c>ea_{slug}/window_{N}h</c>) into
    /// (config station name, window hours). Matches slugs against the
    /// configured rainfall stations case-insensitively so rename drift is
    /// caught as an unresolved entry rather than a silent miss.
    /// </summary>
    private (string? StationName, int WindowHours) ParseCompositeKey(string key)
    {
        var m = Regex.Match(key, @"^ea_(?<slug>.+)/window_(?<w>\d+)h$");
        if (!m.Success) return (null, 0);
        var slug = m.Groups["slug"].Value;
        var window = int.Parse(m.Groups["w"].Value, CultureInfo.InvariantCulture);

        var station = _cfg.Location.Rainfall.Stations
            .FirstOrDefault(s => Slugify(s.Name).Equals(slug, StringComparison.OrdinalIgnoreCase));
        return (station?.Name, window);
    }

    private static string Slugify(string s) => s.ToLowerInvariant()
        .Replace(' ', '_').Replace('-', '_').Replace(',', '_');
}
