<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>WeatherBlend.Scripts.ElementShap</RootNamespace>
    <AssemblyName>element-shap</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WeatherBlend\WeatherBlend.csproj" />
    <PackageReference Include="NetEscapades.Configuration.Yaml" Version="3.1.0" />
  </ItemGroup>

</Project>
